-- AlterTable
ALTER TABLE "RewardTransaction" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "gold" SET DEFAULT 0,
ALTER COLUMN "gold" SET DATA TYPE DOUBLE PRECISION;
