-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dailyTaskLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "habitSlots" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "taskSlots" INTEGER NOT NULL DEFAULT 20;
